# Generated by Django 5.1.7 on 2025-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_course_teacher_course_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
