# Generated by Django 5.1.7 on 2025-05-15 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_submitted_at_submission_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAssignmentSubmission',
            new_name='AssignmentSubmission',
        ),
        migrations.RemoveField(
            model_name='teachercourseassignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachercourseassignment',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='assignment_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='submission_date',
            new_name='submitted_at',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='TeacherCourseAssignment',
        ),
    ]
