# Generated by Django 5.1.7 on 2025-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_question_studentanswer_test_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
