# Generated by Django 5.1.7 on 2025-06-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_testsourcedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsourcedocument',
            name='test_generated',
            field=models.BooleanField(default=False),
        ),
    ]
