# Generated by Django 5.1.7 on 2025-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_question_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
