# Generated by Django 5.1.7 on 2025-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_question_question_type_question_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsourcedocument',
            name='qna_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
