# Generated by Django 5.1.7 on 2025-07-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_testsourcedocument_qna_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qna_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
