# Generated by Django 5.1.7 on 2025-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_aitestsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='correct_option',
            field=models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='qna_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
