# Generated by Django 5.1.7 on 2025-07-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_studentanswer_correct_option_studentanswer_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='feedback',
            new_name='descriptive_answer',
        ),
    ]
