# Generated by Django 5.1.7 on 2025-07-04 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_feedback_studentanswer_descriptive_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='descriptive_answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='qna_id',
        ),
        migrations.CreateModel(
            name='AIStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('descriptive_answer', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
