# Generated by Django 5.2.3 on 2025-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_studentanswer_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudentanswer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aistudentanswer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
